login title:
  enabled: true
  time:
    delay: 2
    fade in: 1
    stay: 3
    fade out: 1
  message:
    first line:
      default: '&a&o{SERVER}'
      first join: '&a&o{SERVER}'
    second line:
      default: '&6Welcome back, {DISPNAME}&6!'
      first join: '&6Welcome to the server, {DISPNAME}&6!'
messages:
  first join: '&a&l+ &e{DISPNAME} &a&ojoined for the first time, welcome!'
  join: '&a&l+ &e{DISPNAME}'
  join silent: '&7&l+ &8{DISPNAME} &7&ojoined the server silently.'
  quit: '&c&l- &e{DISPNAME}'